name: Build and Deploy Agentic Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Deploy application on EC2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LANGSMITH_TRACING: ${{ secrets.LANGSMITH_TRACING }}
          LANGSMITH_ENDPOINT: ${{ secrets.LANGSMITH_ENDPOINT }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}

        run: |
          docker pull $DOCKER_USERNAME/$IMAGE_NAME:latest

          docker stop agentic-chatbot || true
          docker rm agentic-chatbot || true

          docker run -d \
            --name agentic-chatbot \
            --restart unless-stopped \
            -p 8501:8501 \
            -e OPENAI_API_KEY="$OPENAI_API_KEY" \
            -e TAVILY_API_KEY="$TAVILY_API_KEY" \
            -e OPENWEATHER_API_KEY="$OPENWEATHER_API_KEY" \
            -e GOOGLE_API_KEY="$GOOGLE_API_KEY" \
            -e LANGSMITH_TRACING="$LANGSMITH_TRACING" \
            -e LANGSMITH_ENDPOINT="$LANGSMITH_ENDPOINT" \
            -e LANGSMITH_API_KEY="$LANGSMITH_API_KEY" \
            -e LANGSMITH_PROJECT="$LANGSMITH_PROJECT" \
            $DOCKER_USERNAME/$IMAGE_NAME:latest
